spring:
    application:
        name: cqxxxxxxxx.web
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cqxxxxxxxx?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
server:
  port: 9000
logging:
   file: /logs/cqxxxxxxxx.web.log
   level:
     root: debug


#  as default
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

